spring.application.name=superinka-ecosensor-backend

spring.datasource.url=jdbc:postgresql://ep-odd-paper-ai9rzj7d-pooler.c-4.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_n5dlLOBFY7zy

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect