spring.application.name=superinka-ecosensor-backend

# --- BASE DE DATOS (NEON CONSOLE) ---
spring.datasource.url=jdbc:postgresql://ep-odd-paper-ai9rzj7d-pooler.c-4.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / HIBERNATE ---
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# --- SEGURIDAD (AUTH0) ---
logging.level.org.springframework.security=DEBUG
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-6u1q0s2nx3pub4do.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audience=https://ecosensor-api

# --- MONITOREO (ACTUATOR) ---
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# --- CORREO (BREVO SMTP) ---
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=a816b6001@smtp-brevo.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.debug=true
spring.mail.properties.mail.smtp.starttls.enable=true

# --- PROPIEDADES PARA EMAILSERVICE ---
app.mail.from=josealejadrohinojosa@gmail.com
app.mail.from-name=EcoSensor

# --- PAGOS (PAY-ME) ---
payme.merchant-id=TU_MERCHANT_ID
payme.access-key=TU_ACCESS_KEY
payme.api-url=https://sandbox.pay-me.com/api